import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { format } from "sql-formatter";
import {
  Center,
  Header,
  Highlighter,
  Main,
  PrettyHighlight,
  TextArea,
} from "../styles/styles";
import { dracula } from "react-syntax-highlighter/dist/cjs/styles/prism";
import { ToastContainer, toast } from "react-toastify";

const Home: NextPage = () => {
  const [sql, setSql] = useState("");

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setSql(
      format(e.target.value, {
        keywordCase: "upper",
      })
    );
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(sql);
    toast.success("Query copied to clipboard!");
  };

  return (
    <Center>
      <Head>
        <title>@PrettySQL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <div className="ss02">
          <h1>
            Welcome to <a href="https://nextjs.org">@PrettySQL!</a>
          </h1>
          <p>
            How to use @PrettySQL? Enter your SQL query in the input field and
            <strong> click on the formatted SQL to copy</strong>
          </p>
        </div>
      </Header>
      <Main>
        <form>
          <TextArea
            id="sql"
            role="textarea"
            placeholder="Enter your SQL query here"
            onChange={handleChange}
            contentEditable
            cacheMeasurements
            minRows={5}
          ></TextArea>
        </form>
        <PrettyHighlight>
          Your <strong>PrettySQL</strong>
        </PrettyHighlight>
        <div>
          <Highlighter
            language="sql"
            style={dracula}
            onClick={handleCopy}
            id="highlighter"
          >
            {sql}
          </Highlighter>
        </div>
      </Main>
      <ToastContainer />
    </Center>
  );
};

export default Home;
