import type { NextPage } from "next";
import Head from "next/head";
import { useRef, useState } from "react";
import { format } from "sql-formatter";
import styles from "../styles/Home.module.css";
import { Header, Highlighter, Main, TextArea } from "../styles/styles";
import { dracula } from 'react-syntax-highlighter/dist/cjs/styles/prism';

const Home: NextPage = () => {
  const [sql, setSql] = useState("");
  const ref = useRef<HTMLTextAreaElement>(null);

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setSql(
      format(e.target.value, {
        keywordCase: "upper",
      })
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">@Pretty SQL!</a>
        </h1>
        <p className={styles.description}>
          How to use @Pretty SQL ? Insert your SQL query in the input field and
          click on the button <strong>Pretty SQL</strong> to get the result.
        </p>
      </Header>
      <Main>
        <form>
          <TextArea
            id="sql"
            role="textarea"
            placeholder="Enter your SQL query here"
            onChange={handleChange}
            contentEditable
            cacheMeasurements
            minRows={5}
          ></TextArea>
        </form>
        <div>
          <Highlighter language="sql" style={dracula}>
            {sql}
          </Highlighter>
        </div>
      </Main>
    </div>
  );
};

export default Home;
